#!/bin/zsh
#######################
#  ZSHENV FILE V 1.0  #
#######################
# VERSION HISTORY
# V 1.0 (Initial)


#######################
#      DOTFILES       #
#######################



#######################
#    EXPORT PATHS     #
#######################



#######################
#         ZSH         #
#######################


#######################
#  ZSH OPTIMIZATIONS  #
#######################

# Compiling Completion Dumped Files in the Background
{
  # Compile zcompdump, if modified, to increase startup speed.
  zcompdump="/Users/stephane/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!


###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################
