#!/bin/zsh

####################### MACOS ZSHRC FILE v 2.8 #######################
# VERSION HISTORY
# V 1.0 (Initial) - Enable colours, Command Corrections with explicit
#					choice options, History
# V 2.0 - Added Change Directory w/styling
# V 2.1 - Added Starship Command Prompt
# V 2.2 - Added Compinstall Lines
# V 2.3 - Small Code Optimizations
# V 2.4 - Fixed autoload compinit security message
# V 2.5 - Added neofetch to load at every terminal instance
# V 2.6 - Removed starship. Added plugins & theme
# V 2.7 - Added Powerlevel10k config, removed bd plugin. Moved aliases to central file
# V 2.8 - Added lf integrations. Cosmetic cleanup

####################### STAY AT THE TOP #######################
# ENABLE TERMINAL COLOURS
autoload -U colors && colors

# ENABLE POWERLEVEL10K INSTANT PROMPT. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# RUN NEOFETCH every time the terminal opens
neofetch

# DEFAULT ZSH CONFIGURATION Lines Added by Compinstall
zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' insert-unambiguous false
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-suffixes true
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}' 'r:|[._-]=** r:|=**' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}'
zstyle ':completion:*' menu select=10
zstyle ':completion:*' original true
zstyle ':completion:*' preserve-prefix '//[^/]##/y'
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl true
zstyle :compinstall filename '/Users/stephane/.zshrc'

setopt extendedglob nomatch notify
unsetopt beep
bindkey -e

####################### #######################
# LF INTEGRATION @ https://github.com/gokcehan/lf
## Docummentation @ https://pkg.go.dev/github.com/gokcehan/lf?tab=doc
fpath=(/Users/stephane/.config/zsh_plugins/lf/_lf $fpath)

## COMPLETION GENERATOR @ https://github.com/RobSis/zsh-completion-generator
source /Users/stephane/.config/zsh_plugins/zsh-completion-generator.plugin.zsh

### Use LF to switch directories and BIND it to ctrl-e
lfcd () {
    tmp="$(mktemp)"
    lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
    fi
}
bindkey -s '^e' 'lfcd\n'

# Enable TAB COMPLETION. "-i" to silently ignore all insecure files and directories
autoload -Uz compinit          
compinit -i 
_comp_options+=(globdots)		# Include hidden files.

zstyle ':completion:*' menu select

# ALIASES
[ -f "/Users/stephane/.aliases" ] && source "/Users/stephane/.aliases"


####################### ZSH DEFAULT OPTIONS #######################
# Enable COMMAND CORRECTION
setopt correctall

## Display Explicit Choice Options
export SPROMPT="Correct %R to %r? [Yes, No, Abort, Edit] "
export SPROMPT="Correct $fg[red]%R$reset_color to $fg[green]%r$reset_color? [Yes, No, Abort, Edit] "

# Enable HISTORY
setopt appendhistory hist_ignore_all_dups hist_ignore_space hist_reduce_blanks
HISTFILE=/Users/stephane/.zhistory           # History filepath
HISTSIZE=200                                # Maximum events for internal history
SAVEHIST=200                                # Maximum events in history file

# Enable CHANGE DIRECTORIES
setopt auto_cd auto_pushd pushd_ignore_dups pushdminus

zstyle ':completion:*:*:cdr:*:*' menu selection
zstyle ':completion:*' recent-dirs-insert both
zstyle ':chpwd:*' recent-dirs-max 50
zstyle ':chpwd:*' recent-dirs-default true
zstyle ':chpwd:*' recent-dirs-pushd true

####################### PLUGINS & THEMES  #######################
# Auto-Completions
# Github Repo @ https://github.com/zsh-users/zsh-completions
# Completion List @ https://github.com/zsh-users/zsh-completions/tree/master/src
source /Users/stephane/.config/zsh_plugins/zsh-completions.plugin.zsh

# Z @ https://github.com/rupa/z
source /Users/stephane/.config/zsh_plugins/z.sh

# Zsh Autosuggestions @ https://github.com/zsh-users/zsh-autosuggestions
source /Users/stephane/.config/zsh_plugins/zsh-autosuggestions.zsh

# Powerlevel10k Theme @ https://github.com/romkatv/powerlevel10k
# Run setup with "p10k configure"
source /Users/stephane/.config/zsh_plugins/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

####################### ALWAYS LAST #######################
# Zsh Syntax Highlighting @ https://github.com/zsh-users/zsh-syntax-highlighting
source /Users/stephane/.config/zsh_plugins/zsh-syntax-highlighting.zsh